### ISSUE TITLE
error ' No matching function for call to 'toCv' '

### ISSUE THREAD

**Issue by FlorentDeloison** [kylemcdonald/ofxCv#140]
Hello,
when I try to build my program, i get this error:

/Users/florentdeloison/Downloads/of_v0.8.4_osx_release/addons/ofxCv/libs/ofxCv/include/ofxCv/Utilities.h:230:10: No matching function for call to 'toCv'

Maybe I didn't install properly the add ons, or I forgot something ?

**Comment by josephmwells** [comment]
Can you post what the solution was ?
