### ISSUE TITLE
Errror C2665: 'ofxCv::toCv' : none of the 9 overloads could convert all the argument types...

### ISSUE THREAD

**Issue by kennyallau** [kylemcdonald/ofxCv#143]
Good day Kyle,

I came across with this compile error, not sure how to fix it:

..\openFrameworks\of_v0.8.3_vs_release\addons\ofxCv\libs\ofxCv\include\ofxCv/Utilities.h(230): error C2665: 'ofxCv::toCv' : none of the 9 overloads could convert all the argument types

2>         ..\openFrameworks\of_v0.8.3_vs_release\addons\ofxCv\libs\ofxCv\include\ofxCv/Utilities.h(225): could be 'cv::Mat ofxCv::toCv(cv::Mat &)'
2>          ..\openFrameworks\of_v0.8.3_vs_release\addons\ofxCv\libs\ofxCv\include\ofxCv/Utilities.h(232): or       'cv::Mat ofxCv::toCv(ofMesh &)'
2>          C:\Users\Ascend\Desktop\NEX360\openFrameworks\of_v0.8.3_vs_release\addons\ofxCv\libs\ofxCv\include\ofxCv/Utilities.h(233): or       'cv::Point2f ofxCv::toCv(ofVec2f)'
2>          ..\openFrameworks\of_v0.8.3_vs_release\addons\ofxCv\libs\ofxCv\include\ofxCv/Utilities.h(234): or       'cv::Point3f ofxCv::toCv(ofVec3f)'
2>          ..\openFrameworks\of_v0.8.3_vs_release\addons\ofxCv\libs\ofxCv\include\ofxCv/Utilities.h(235): or       'cv::Rect ofxCv::toCv(ofRectangle)'
2>          ..\openFrameworks\of_v0.8.3_vs_release\addons\ofxCv\libs\ofxCv\include\ofxCv/Utilities.h(236): or       'std::vector<_Ty> ofxCv::toCv(const ofPolyline &)'

**Comment by AkiHo57** [comment]
Hey,I have got this error too. Now I'm using Windows 8.1 64bit, VS2012, and I run the [`ofxKinect2ProjectorCalibration`](https://github.com/Kj1/ofxKinect2ProjectorCalibration) Addon with it.
I have tried all the vision but it doesn't  work. Could you please tell me which one is suitable,or should I change my OF vision?
