### ISSUE TITLE
Current label issue(?)

### ISSUE THREAD

**Issue by zrrz** [kylemcdonald/ofxCv#145]
I'm trying to track some shapes using the contourFinder tracker. This code snippet just logs some info, and I put the output pulled from the middle of my tracking sequence. So here's my question/issue? From what I've read of the Tracker, it is supposed to keep previous contours and their labels and put them into current. Following this, if I have one object on the screen, I would expect currentLabels to be 1. That is not the case with my output. I've tried many different variations and tweaking, and also tried to get it working with the TrackerFollower, with the same results. What's confusing to me is that age works fine, so it IS tracking, just not putting them into current. 

Is this an issue, or it is by design? and if its by design, what it the proper way to use it so I can get velocity out of it?

        for(int i = 0; i < contourFinder.size(); i++) {
            ofxCv::RectTracker& tracker = contourFinder.getTracker();
            int label = contourFinder.getLabel(i);
            int age = contourFinder.getTracker().getAge(label);
            const cv::Rect& current = tracker.getSmoothed(label);
            
            ofVec2f curPos = ofxCv::toOf(current).getCenter();
            
            string notice = "curLabels: " + ofToString(tracker.getNewLabels().size())
            + " newLabels: " + ofToString(tracker.getNewLabels().size())
            + "|prevLabels: " + ofToString(tracker.getPreviousLabels().size())
            + "|deadLabels: " + ofToString(tracker.getDeadLabels().size())
            + "|label: " + ofToString(label)
            + "|age: " + ofToString(age)
            + "|pos: " + ofToString(curPos)
            + "|vel: " + ofToString(velocityMap[label]);
            
            ofLogNotice(ofToString(notice));
        }

        // Output:
        [notice ] curLabels: 0 newLabels: 0|prevLabels: 1|deadLabels: 0|label: 4|age: 98|pos: 152, 0|vel: 0, 0: 
        [notice ] curLabels: 0 newLabels: 0|prevLabels: 1|deadLabels: 0|label: 4|age: 99|pos: 159, 0|vel: 0, 0: 
        [notice ] curLabels: 0 newLabels: 0|prevLabels: 1|deadLabels: 0|label: 4|age: 100|pos: 172, 0|vel: 0, 0: 
        [notice ] curLabels: 0 newLabels: 0|prevLabels: 1|deadLabels: 0|label: 4|age: 101|pos: 192, 0|vel: 0, 0: 
        [notice ] curLabels: 0 newLabels: 0|prevLabels: 1|deadLabels: 0|label: 4|age: 102|pos: 209, 0|vel: 0, 0:

**Comment by zrrz** [comment]
I actually managed to solve my velocity issue. But the question still stands: how is current supposed to be used? Or is it just for the internal track method?

**Comment by kylemcdonald** [comment]
it looks like you have a typo `string notice = "curLabels: " + ofToString(tracker.getNewLabels().size())` should be `string notice = "curLabels: " + ofToString(tracker.getCurrentLabels().size())`

please re-open the issue or post another one if you still have a problem. i wrote the `Tracker` carefully but there may still be bugs!
