### ISSUE TITLE
OpenCV 3.0 support

### ISSUE THREAD

**Issue by nylki** [kylemcdonald/ofxCv#149]
I was wondering if working with openCV Version 3.0 already works with ofxCV or if it is planned in the near-mid future.

**Comment by tpltnt** [comment]
I am also interessted in that.

**Comment by kylemcdonald** [comment]
i would love to include opencv 3.0!

but ofxCv is based on whatever version of opencv that OF ships with. so the issue to watch will be this one:

https://github.com/openframeworks/openFrameworks/issues/3893
