### ISSUE TITLE
class ofBaseHasPixels_<unsigned char>’ has no member named ‘getPixelsRef’

### ISSUE THREAD

**Issue by trixymoon** [kylemcdonald/ofxCv#150]
After commit 0ecd3cf9a7f8fc488efb9259cf75af4c61c5b4e7
where the line 230 in file "libs/ofxCv/include/ofxCv/Utilities.h"
<code>return toCv(img.getPixels());</code>
where changed in:
<code>return toCv(img.getPixelsRef());</code>

ofxCv fail to compile against OF v0.9.0.

openFrameworks/addons/ofxCv/libs/ofxCv/include/ofxCv/Utilities.h:230:33: error: ‘class ofBaseHasPixels_<unsigned char>’ has no member named ‘getPixelsRef’
   return toCv(img.getPixelsRef());

I am using the latest version of the open framework cloned from github.

Sorry for my bad English.

**Comment by kylemcdonald** [comment]
please use https://github.com/kylemcdonald/ofxCv/tree/develop which is up to date with https://github.com/openframeworks/openFrameworks/tree/master

**Comment by trixymoon** [comment]
Ok, thanks a lot. It's working flawless.
