### ISSUE TITLE
Request to finish wrapper for matchShapes

### ISSUE THREAD

**Issue by div1234522** [kylemcdonald/ofxCv#151]
In libs/ofxCv/include/ofxCv/ContourFinder.h, "cv::matchShapes - similarity between two contours" is marked as Todo. I need this function for my project, so I tried using the OpenCv variant by converting all the Images to Mat using the toCv function. I still get assertion error, as the matrices have checkVector(2) = -1 and depth = 0. I also tried to start directly from Mat, using cv::Canny and cv::findContours and pass them to cv::matchShapes, but still an assertion error comes. Please help.

**Comment by div1234522** [comment]
Got it. matchShapes used vector<cv::Point> instead of vector < vector <cv::Point>>
Hope that helps someone.

**Comment by kylemcdonald** [comment]
thanks! if you have a moment please add your wrapper function to ofxCv as a pull request :)

glad you got it working for your project!

**Comment by div1234522** [comment]
Sure. That's the least I can do for all your efforts. Would do it during the weekend. :)
