### ISSUE TITLE
error: ‘class ofTextureData’ has no member named ‘glTypeInternal’

### ISSUE THREAD

**Issue by henryjoye** [kylemcdonald/ofxCv#153]
I am using ofxCv in ofxKinectProjectorToolkit in OpenFrameworks. When I compile ofxKinectProjectorToolkit  examples such as  "calibration", I got errors as follows:
......
../../../addons/ofxCv/libs/ofxCv/include/ofxCv/Utilities.h:43:41: error: ‘class ofTextureData’ has no member named ‘glTypeInternal’
         int type = tex.getTextureData().glTypeInternal;
                                         ^
../../../addons/ofxCv/libs/ofxCv/include/ofxCv/Utilities.h: In function ‘int ofxCv::getChannels(ofTexture&)’:
../../../addons/ofxCv/libs/ofxCv/include/ofxCv/Utilities.h:102:41: error: ‘class ofTextureData’ has no member named ‘glTypeInternal’
         int type = tex.getTextureData().glTypeInternal;

src/ofApp.cpp:94:47: error: ‘class ofxCvColorImage’ has no member named ‘getPixelsRef’
             cvRgbImage = ofxCv::toCv(rgbImage.getPixelsRef());
........

They are mainly on type problems. I think this is mainly related to different package version compatibility problems. I got all sources from Github as follows:

ofxKinectProjectorToolkit: https://github.com/genekogan/ofxKinectProjectorToolkit
ofxCv: https://github.com/kylemcdonald/ofxCv
OpenFrameworks:
https://github.com/openframeworks/openFrameworks

Would you please mind to give any suggestions on these errors?

Thank you very much!

**Comment by henryjoye** [comment]
I searched from ofx document and changed glTypeInternal to glInternalFormat, changed getPixelsRef to getPixels. Then everything is ok.

**Comment by kylemcdonald** [comment]
to use ofxCv with the latest version of OF, please see the `develop` branch https://github.com/kylemcdonald/ofxCv/tree/develop
