### ISSUE TITLE
oF 0.8.4 compatibility

### ISSUE THREAD

**Issue by woutgg** [kylemcdonald/ofxCv#156]
In oF 0.8.4, [toOf()](https://github.com/kylemcdonald/ofxCv/blob/master/libs/ofxCv/include/ofxCv/Utilities.h#L290) does not compile, it should read `toOf(mat, img.getPixelsRef());`.

**Comment by kylemcdonald** [comment]
thanks. closed by 005c0a7ae35e45fc505546599e06ff3b9724ac11 and i think i fixed some other 0.8.4-related bugs too.
