### ISSUE TITLE
some example's aren't compiling > directory not found for option '-L/Users/kyle/....

### ISSUE THREAD

**Issue by jBachalo** [kylemcdonald/ofxCv#158]
Getting this error on the example-gesture' project.
Possibly a hard coded path somewhere?

ld: warning: directory not found for option '-L/Users/kyle/Documents/openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx'

**Comment by kylemcdonald** [comment]
fixed it, thanks!
