### ISSUE TITLE
some examples not compiling>  ofxAutoControlPanel.h file not found

### ISSUE THREAD

**Issue by jBachalo** [kylemcdonald/ofxCv#160]
In the example-coherent-lines Project in the main.cpp file get the following error when I try to compile

ofxAutoControlPanel.h file not found

**Comment by kylemcdonald** [comment]
you'll have to download this and add it yourself. i added a note to the readme. when the next version of OF is released i will upgrade to ofxGui (and it's already in the `develop` branch)

**Comment by jBachalo** [comment]
Thanks Kyle!
