### ISSUE TITLE
'opencv2/opencv.hpp' file not found

### ISSUE THREAD

**Issue by mikevanis** [kylemcdonald/ofxCv#167]
Hi! I downloaded ofxCv as described in the README (cloned repo into addons). I then built a new project with the of projectGenerator and initially just wanted to test that everything is up and running. Therefore, my ofApp just opens an ofVideoGrabber and tries to draw the output. When I try to run, I get the following compilation error: `'opencv2/opencv.hpp' file not found `. This seems to root down to `ofxCv.h` located in `addons/ofxCv/src/ofxCv.h`.

Any help would be greatly appreciated!

EDIT: this is on Xcode 7.0.1.

Here is my ofApp.h:
```
#pragma once

#include "ofMain.h"
#include "ofxCv.h"

class ofApp : public ofBaseApp{
public:
    void setup();
    void update();
    void draw();

    ofVideoGrabber cam;
    //cv::Mat empty;
};
```

Here is my ofApp.cpp:
```
#include "ofApp.h"

//--------------------------------------------------------------
void ofApp::setup(){
    cam.initGrabber(320, 240);
}

//--------------------------------------------------------------
void ofApp::update(){
    cam.update();
}

//--------------------------------------------------------------
void ofApp::draw(){
    cam.draw(0, 0);
}
```

**Comment by danamajid** [comment]
Same problem here. Did you manage to solve this issue?

**Comment by kylemcdonald** [comment]
this is a bug with the project generator. currently it's not processing addon dependencies https://github.com/openframeworks/projectGenerator/pull/90

to make a working project, please manually add ofxOpenCv with the project generator.

i'll leave this issue open until https://github.com/openframeworks/projectGenerator/pull/90 is merged and the next version of OF is released.

**Comment by kylemcdonald** [comment]
this is working for me now.

**Comment by bboyslak** [comment]
I already try all this, and still getting 'opencv2/opencv.hpp' file not found

**Comment by kylemcdonald** [comment]
@bboyslak please post more info.

0. what operating system version?
0. what version of OF?
0. where did you put the ofxOpenCv folder?
0. which example are you running?
0. did you generate the project file with the project generator, or some other way?

**Comment by bboyslak** [comment]
Mac OS 10.10.5
oF 0.9.3
ofxOpenCv folder is in /addons
im trying to run CREA for oF 0.9 ( https://github.com/fabiaserra/crea/tree/OF0.9.0 )
app was already done by fabiaserra i just download everything and run, but the only error i get is 'opencv2/opencv.hpp' file not found

**Comment by Davidmarcell** [comment]
Same issue as you @bboyslak 
![screen shot 2016-05-18 at 8 27 57 am](https://cloud.githubusercontent.com/assets/4370458/15338082/72b3599a-1cd2-11e6-9805-3a4bddd17eec.png)

However, I'm using OF0.8.4

**Comment by LadyK** [comment]
Same issue...
1. OS X 10.10.5
2. oF v 0.9.8
3. Error occurs when creating the project through the project generator OR manually putting the ofxOpenCv in the addons folder in XCode project
4. I'm running the graphics example (super basic ellipse) with the inclusion of #include "ofxCv.h" in ofApp.h file.
5. unsuccessful with the project generator and with doing it manually.
6. XCode 7.2.1

**Comment by jjuliaa** [comment]
I found  a quick (possibly dirty) solution to this. In the file throwing the error I deleted the "#include opencv2/opencv.hpp" line. Then copied the lines of code located in opencv.hpp and put them directly where the error was thrown.  Since that piece of code seems to mostly just be including other files, it works to just pass them in. The lines are:

#include "opencv2/core.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/photo.hpp"
#include "opencv2/video.hpp"
#include "opencv2/features2d.hpp"
#include "opencv2/objdetect.hpp"
#include "opencv2/calib3d.hpp"
#include "opencv2/imgcodecs.hpp"
#include "opencv2/videoio.hpp"
#include "opencv2/highgui.hpp"
#include "opencv2/ml.hpp"

Seems to work for me now at least, can further clarify if it helps anyone. Thanks Kyle for the brilliant work!
