### ISSUE TITLE
  hey! both example-difference-columns  and example-difference won't compile 

### ISSUE THREAD

**Issue by cyrstem** [kylemcdonald/ofxCv#182]
it  show  this error utilities.h 
// allocation
	// only happens when necessary
	template <class T> inline void allocate(T& img, int width, int height, int cvType) {
        if (!img.isAllocated() || //here ?
            getWidth(img) != width ||
            getHeight(img) != height ||
            getCvImageType(img) != cvType)
        {
            img.allocate(width, height, getOfImageType(cvType));
        }
	}

OF/of_v0.9.0_osx_release/addons/ofxCv/libs/ofxCv/include/ofxCv/Utilities.h:173:18: No member named 'isAllocated' in 'ofVideoGrabber'

**Comment by gdpl** [comment]
On RPI2 (oF 0.9.0 for  arm7 release) has the same problem.

**Comment by cyrstem** [comment]
any idea how to fix  this?

**Comment by ShadowMitia** [comment]
Changing this line `absdiff(previous, cam, diff);` to this `absdiff(cam, previous, diff);` fixed the example for me. (With oF 0.9.2)

**Comment by cyrstem** [comment]
yay, thanks   that worked  !!

**Comment by kylemcdonald** [comment]
most recent changes make these modifications to the examples. thanks @ShadowMitia!

closing this issue.
