### ISSUE TITLE
calibration.ccp - unknown type name 'ofXML'

### ISSUE THREAD

**Issue by RichardBoyder** [kylemcdonald/ofxCv#198]
hi guys

I'm having a issue building my project for ios. the code stops at 

ofXml xml; (line 162)

it sais Unknown type name 'ofXml'

why is this? what can i do to correct thing.

when i type 

ofFile myFile

its fine why isn't it accepting this xml variable type initialisation?

**Comment by b2b** [comment]
Hi!
I have the same problem on of 0.9.3 qtCreator 3.6.1 Ubuntu.
Here is the out put for example-face
```
/OF/addons/ofxCv/libs/ofxCv/src/Calibration.cpp: In member function ‘void ofxCv::Calibration::loadLcp(std::__cxx11::string, float, bool)’:
/home/bkb/programok/OF/addons/ofxCv/libs/ofxCv/src/Calibration.cpp:161:9: error: ‘ofXml’ was not declared in this scope
         ofXml xml;

/OF/addons/ofxCv/libs/ofxCv/src/Calibration.cpp:162:23: error: **‘xml’ was not declared in this scope
         bool loaded = xml.load(ofToDataPath(filename, absolute));**
                       ^
Process failed with exit code 1.
The following products could not be built for configuration qtc_Desktop_6681c16b-debug:
	example-face
```

Please help in resolving this issue.
Dan

**Comment by ruvindad** [comment]
Reverting back to commit 85f8a34a2ed07db44d4b97c14c8f5019f3bcfb71 avoids this problem.

**Comment by RichardBoyder** [comment]
thank you

**Comment by b2b** [comment]
Hi,
this is how I could compile the source code:

I've added:

> #include "ofXml.h"

to file
**/OF/addons/ofxCv/src/ofxCv.h**
now ofxCv.h looks like this:

```
>  #pragma once
>  #include "ofXml.h"
>  // cv
>  #include "opencv2/opencv.hpp"
> 
>  // ofxCv
```

I could compile example-face on OF 0.9.3 qtCreator 3.6.1 Ubuntu.
I've tried to add #include "ofXml.h" into files: main.cpp ofApp.cpp ofApp.h without success and I've tried this solution https://github.com/kylemcdonald/ofxCv/issues/198 but it didn't work.

Dan
