### ISSUE TITLE
vector<bool> allholes out-of-range error in ContourFinder

### ISSUE THREAD

**Issue by musiko** [kylemcdonald/ofxCv#202]
In CountourFinder `ofxCv/libs/ofxCv/src/ContourFinder.cpp`, Line 120:

> `holes.push_back(allHoles[allIndices[i]]);`

if `minArea` = 0 and `maxArea`= 1,
boolean `needMinFilter` and `needMaxFilter` will then be false.
In this case, `vector<bool> allHoles` is always empty, and the above codes will throw vector out-of-range error when `allIndices` is not empty.

**Comment by kylemcdonald** [comment]
Thanks for taking note of this. While working with ContourFinder recently I realized there are some other problems like this (out of range errors). I will take a more thorough look at some point, and appreciate any PRs in the meantime.

**Comment by kylemcdonald** [comment]
possibly, hopefully closed by #209

if you have any time to check please let me know if this fixes your problems! thanks :)

**Comment by musiko** [comment]
@kylemcdonald sorry for late reply, #209 fixed the issue in master version (0.10.0).
The issue still exists in stable version (OF0.9.8).
