### ISSUE TITLE
Compilation error in project using ofxImGui on Windows

### ISSUE THREAD

**Issue by mruegenberg** [kylemcdonald/ofxCv#205]
In a project that also includes [ofxCv](https://github.com/kylemcdonald/ofxCv), I get the following compilation error:

~~~~
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(936,5): warning MSB8027: Two or more files with the name of Helpers.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are ..\..\..\addons\ofxCv\libs\ofxCv\src\Helpers.cpp, ..\..\..\addons\ofxImGui\src\Helpers.cpp.
~~~~

I guess the error is pretty self-explanatory. MSVC can't handle the same filename existing twice in the same project and I indeed get a linker error later on.

The solution would be for either ofxCv or ofxImGui or both to rename Helpers.cpp/.h

See also the corresponding [ofxImGui issue](https://github.com/jvcleave/ofxImGui/issues/48).

**Comment by kylemcdonald** [comment]
It looks like there is a VS-specific solution to this problem. http://www.setoreaustralia.com/msb8027-two-or-more-files-with-the-name-of-texture-cpp-will-produce-outputs-to-the-same-location/
