### ISSUE TITLE
'imatrix' was not declared in this scope

### ISSUE THREAD

**Issue by gilFuser** [kylemcdonald/ofxCv#206]
Hi.
I'm trying to build a project I made in the end of 2016 and I'm having some trouble.

At first all the includes (and maybe I should make another issue to it) are failing. As a dirty workaround I'm giving the whole path to the files.

Then I got this error:

/home/gil/of_v0.9.7_linux64_release/addons/ofxCv/libs/CLD/include/CLD/fdog.h:5: error: variable or field ‘GaussSmoothSep’ declared void
 extern void GaussSmoothSep(imatrix& image, double sigma);
                            ^~~~~~~

Followed to this one:

/home/gil/of_v0.9.7_linux64_release/addons/ofxCv/libs/CLD/include/CLD/fdog.h:5: error: ‘imatrix’ was not declared in this scope

I tried with oF 9.7, 9.8 and with the nightly build. In the nightly build I didn't have the includes problem. I'm using Qt Creator 4.1 on Linux. I also tried using the Project Generator and then 'make' in the terminal.

I goggled searching for a solution but got no luck.

Thank you in advance for any help.

Best regards,
Gil

**Comment by kylemcdonald** [comment]
Please try again with the project generator an 0.9.8. I just merged some changes that should make this work again.
