### ISSUE TITLE
strange compile errors ofxCv on win10 msys2 ofv0.9.8 

### ISSUE THREAD

**Issue by 0Kraft** [kylemcdonald/ofxCv#213]
Hi there,
i get some errors when i try to compile an ofxCv example in my win10 - msys2 - ofv0.9.8 environment:

`In file included from F:/Arbeit/Programming/of_v0.9.8_msys2_release/libs/openFrameworks/ofMain.h:39:0,
                 from F:/Arbeit/Programming/of_v0.9.8_msys2_release/apps/myApps/example-coherent-lines/src/ofApp.h:3,
                 from F:/Arbeit/Programming/of_v0.9.8_msys2_release/apps/myApps/example-coherent-lines/src/main.cpp:1:
F:/Arbeit/Programming/of_v0.9.8_msys2_release/libs/openFrameworks/communication/ofArduino.h:62:57: error: expected identifier before numeric constant
 #define SHIFT                                           0x05 // shiftIn/shiftOut mode
                                                         ^
F:/Arbeit/Programming/of_v0.9.8_msys2_release/libs/openFrameworks/communication/ofArduino.h:62:57: error: expected '}' before numeric constant
F:/Arbeit/Programming/of_v0.9.8_msys2_release/libs/openFrameworks/communication/ofArduino.h:62:57: error: expected unqualified-id before numeric constant
In file included from C:/msys64/mingw32/include/opencv2/viz.hpp:49:0,
                 from C:/msys64/mingw32/include/opencv2/opencv.hpp:101,
                 from F:/Arbeit/Programming/of_v0.9.8_msys2_release/addons/ofxCv/src/ofxCv.h:4,
                 from F:/Arbeit/Programming/of_v0.9.8_msys2_release/apps/myApps/example-coherent-lines/src/ofApp.h:5,
                 from F:/Arbeit/Programming/of_v0.9.8_msys2_release/apps/myApps/example-coherent-lines/src/main.cpp:1:
C:/msys64/mingw32/include/opencv2/viz/types.hpp:237:34: error: expected ')' before 'action'
             KeyboardEvent(Action action, const String& symbol, unsigned char code, int modifiers);
                                  ^~~~~~
C:/msys64/mingw32/include/opencv2/viz/types.hpp:273:1: error: expected declaration before '}' token
 } /* namespace cv */`

The strange thing is: all of the ofxCv-files compile succesfully, the errors appear while compiling main.cpp. So i thought it must be an issue concerning the already-compiled oF-lib. But all the standard-examples compile and execute succesfully. I'm quite confused right now. Does it even have something to do with ofxCv?

Greets

**Comment by orgicus** [comment]
Getting the same errors on Windows 8 - mysys2 - ofxv0.9.8 using the stable branch

It's confusing why ofArduino.h is used here at all.

Any tips on how compile ofxCv on Windows ? :man_dancing:

**Comment by orgicus** [comment]
I've gone for [VisualStudio](http://openframeworks.cc/setup/vs/) instead of msys2 and managed to use ofxCv on Windows this way. HTH
