### ISSUE TITLE
problem with "glm"

### ISSUE THREAD

**Issue by jing1234** [kylemcdonald/ofxCv#214]
Hi, 
I try to run the example. But there are some problems. 
Kalman.h(28): error C3646:
Kalman.h(28): error C2653: “glm”
Flow.h(137): error C2238:
There are always problem with''glm''.  Is therre any other people meet this problems?
Anybody can help me ?

Thanks so much

**Comment by jing1234** [comment]
I just used the wrong version. It now can perfect work . Thanks so much.

**Comment by Mehrbano** [comment]
hi can you explain regarding this "version" issue? because I m facing the same

**Comment by fishkingsin** [comment]
check this https://github.com/kylemcdonald/ofxCv/issues/208
