### ISSUE TITLE
Use of undeclared identifier ‘glm’

### ISSUE THREAD

**Issue by SasanBhrm** [kylemcdonald/ofxCv#223]
I am using OF 0.9.8 on OSX sierra with Xcode 8.2 and I try to run examples in stable version in here https://github.com/kylemcdonald/ofxCv/tree/stable1 
but I am getting this error ,

any help would be appreciated

thanks,

**Comment by danbz** [comment]
this appeared as a compile error when i moved from one dev machine to another using of0.9.8, I reverted the version of ofxCV I was using from Master to Stable and the problem was resolved

**Comment by pseudospencer** [comment]
Will second this - didn't realize that after cloning the repo I was on the master branch. Thanks @danbz
