### ISSUE TITLE
Loading from YAML file always fails

### ISSUE THREAD

**Issue by anselanza** [kylemcdonald/ofxCv#227]
I have used the example-calibration app as is, caibrated my camera and it saves `bin/data/calibration.yml` as expected.

But when I try to load this same data (simply using `calibration.load(calibration.yml`) then I get the following at runtime:

```
OpenCV Error: Null pointer (Null pointer to reader or destination array) in cvReadRawDataSlice, file /home/stephen/Downloads/opencv/modules/core/src/persistence.cpp, line 3230
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/stephen/Downloads/opencv/modules/core/src/persistence.cpp:3230: error: (-27) Null pointer to reader or destination array in function cvReadRawDataSlice

```
It seems that the YAML is valid, but something is up with the calibration file that was generated by the same app... How is that even possible?

**Comment by anselanza** [comment]
Eek, seems to be a duplicate of https://github.com/kylemcdonald/ofxCv/issues/175 which has been fixed, but Pull Request never approved :(

**Comment by kylemcdonald** [comment]
i think this should be fixed now.

**Comment by anselanza** [comment]
Thanks for following up!
