### ISSUE TITLE
complie error with emptyproject

### ISSUE THREAD

**Issue by buzzhoot** [kylemcdonald/ofxCv#234]
i can't  complie an empty project with ofxcv ofxopencv
but the example seems fine
vs2015 got error

Error	LNK2019	unresolved external symbol "void __cdecl ofxCv::applyMatrix(class ofMatrix4x4 const &)" (?applyMatrix@ofxCv@@YAXABVofMatrix4x4@@@Z) referenced in function "public: void __thiscall ofxCv::Calibration::draw3d(int)const " (?draw3d@Calibration@ofxCv@@QBEXH@Z)	cvtest	D:\13OpenframeWorks\of_v0.9.8_vs_release\apps\myApps\cvtest\Calibration.obj	

Error	LNK2019	unresolved external symbol "class ofMatrix4x4 __cdecl ofxCv::makeMatrix(class cv::Mat,class cv::Mat)" (?makeMatrix@ofxCv@@YA?AVofMatrix4x4@@VMat@cv@@0@Z) referenced in function "public: void __thiscall ofxCv::Calibration::draw3d(int)const " (?draw3d@Calibration@ofxCv@@QBEXH@Z)	cvtest D:\13OpenframeWorks\of_v0.9.8_vs_release\apps\myApps\cvtest\Calibration.obj

**Comment by kylemcdonald** [comment]
is this still a problem? please comment if so.

**Comment by xarthurx** [comment]
Still a problem.

**Comment by xarthurx** [comment]
@kylemcdonald  VS2017, master branch.
