### ISSUE TITLE
PCA application on single face images

### ISSUE THREAD

**Issue by alana92** [kylemcdonald/ofxCv#238]
Would it be possible to do a PCA application similar to, say, the example-highpass application where instead of contrast and size the user has the option of controlling the range of components displayed for a single image?

I've adapted the highpass-example to use a single image input instead of camera input and added a class for a lowpass filter to allow the user to view the effects of both lowpass and highpass filters on a single image.

So I'm specifically interested in applying PCA to single face views (only one image per face), so that the user has the option of setting the range of components they want to view (i.e. from components a to components b).

Would appreciate any leads.

**Comment by kylemcdonald** [comment]
sorry! i can only reply to bugs here, not discussion.
