### ISSUE TITLE
Xcode Unknown type name 'vector'; did you mean 'std::vector'?

### ISSUE THREAD

**Issue by omarojo** [kylemcdonald/ofxCv#244]
Im having this issue in Xcode 9.  Search Header Paths are okay. 

<img width="1391" alt="screen shot 2018-03-15 at 3 56 30 am" src="https://user-images.githubusercontent.com/995265/37459363-0c870992-2805-11e8-8790-140e26885c15.png">

**Comment by kylemcdonald** [comment]
that bug has been fixed, please update your code:

https://github.com/kylemcdonald/ofxCv/blob/master/libs/ofxCv/include/ofxCv/Tracker.h#L115-L117
