### ISSUE TITLE
OF 10 issue with example-flow-distort-shader 

### ISSUE THREAD

**Issue by cyrstem** [kylemcdonald/ofxCv#246]
hey i got this issue trying to compile that example :
`OF/of_v0.10.0_osx_release/addons/ofxCv/example-flow-distort-shader/src/MotionAmplifier.h:43:32: No viable conversion from 'tvec2<float, (glm::precision)0U>' to 'const glm::tvec3<float, 0>'`
on this line:
```
 for(int x = 0; x < xSteps; x++) {
                mesh.addVertex(ofVec2f(x, y) * stepSize / rescale);
            }
```

**Comment by kylemcdonald** [comment]
should be fixed now.
