### ISSUE TITLE
'ofVideoBaseTypes.h' file not found

### ISSUE THREAD

**Issue by jacqueline5566** [kylemcdonald/ofxCv#248]
I download ofxCv,it tells me 'ofVideoBaseTypes.h' file not found, could anyone tell me how to solve it?

**Comment by AndreasRef** [comment]
Same issue here. Anybody found a solution?

**Comment by pierdr** [comment]
Same issue.

**Comment by kkshmz** [comment]
Not seeing this on OF 0.10
macOS 10.13.5, xcode 9.2, you guys using OF from git?

**Comment by kylemcdonald** [comment]
Closing unless someone can reproduce.
