### ISSUE TITLE
Inverted color channels (RGB vs BGR)

### ISSUE THREAD

**Issue by nicholasc** [kylemcdonald/ofxCv#258]
I am trying to display a matrix retrieved from an OpenCV VideoCapture object using the following code:
```cpp
cv::Mat mat;
ofImage img;
cv::VideoCapture instance;

mat = ofxCv::toCv(img);

instance.open(0);
instance.read(mat);
img.update();
```

My draw method simply draws the image 
```cpp
img.draw(0, 0);
```

It looks like the Blue & Red channels are inverted as if the Mat was BGR and the ofImage RGB.
<img width="638" alt="screen shot 2019-01-30 at 9 08 16 pm" src="https://user-images.githubusercontent.com/2378304/52025664-36f16580-24d3-11e9-8f00-155cbf382ca6.png">

Any idea what might be the cause?
OpenCV v3.4.2

**Comment by nicholasc** [comment]
If I convert the color before updating the ofImage it works:
```cpp
ofxCv::convertColor(_mat, _mat, CV_BGR2RGB);
```

I don't believe this is the normal behavior though.

**Comment by kylemcdonald** [comment]
this is the normal behavior. OpenCV is BGR-native by default, while OF is RGB-native. ofxCv lives in OF-land, so we do not ever convert RGB-BGR inside ofxCv functions.
