### ISSUE TITLE
issue running example on linux.

### ISSUE THREAD

**Issue by rdtor** [kylemcdonald/ofxCv#264]
I am using openCV 4.0.1 in openFrameworks 0.10.1
opt/openFrameworks/addons/ofxCv/libs/CLD/src/ETF.cpp: In member function ‘void ETF::Smooth(int, int)’:
/opt/openFrameworks/addons/ofxCv/libs/CLD/src/ETF.cpp:205:6: warning: unused variable ‘MAX_GRADIENT’ [-Wunused-variable]
int MAX_GRADIENT = -1;
^~~~~~~~~~~~

**Comment by kylemcdonald** [comment]
Please try again on 0.11.0
