### ISSUE TITLE
Custom Tracker Problem

### ISSUE THREAD

**Issue by philworthy** [kylemcdonald/ofxCv#84]
Hi Kyle. I'm trying to implement a custom tracker but running into some issues.

I'd like to track convexity defects in a contour, so my thought was to create a 'ContourSection' class that takes a reference to the Polyline contour along with start and end indexes of the convexity defect. (Note: I'm able to get convexity defects as indices using OpenCV2.4.3 and I've added a method to ContourFinder to return these). Here's my 'ContourSegment' class (which calculates the position of the tracking point using the contour and indexes passed into it):

``` c++
ContourSegment::ContourSegment( const ofPolyline *contour, int startIndex, int endIndex )
    :contour(contour)
    ,startIndex(startIndex)
    ,endIndex(endIndex) {
        trackPoint = (contour->operator[](startIndex) + contour->operator[](endIndex)) * 0.5;
}
```

All good so far (I think), though I did have some issues using references of contour so I'm using pointers at the moment (hopefully that has nothing to do with this issue but forgive me if stupid as I'm still wrapping my head around the best practices with that stuff).
So anyway, now I extend your Follower class to make my own that takes 'ContourSegment' as its object to track (as opposed to Point or Rect). This will allow me to use the contour and start/end indexes to draw stuff on that section of contour later, as the tracker will pass my 'ContourSegment' into my 'ContourSegmentFolower'. Here's the Follower (simplified):

``` c++
class ConcaveSegmentFollower : public ofxCv::Follower<ContourSegment> {
protected:
    float startedDying;
public:
    ConcaveSegmentFollower()
    :startedDying(0) {
    }
    void setup(const ContourSegment& segment);
    void update(const ContourSegment& segment);
    void draw();
    void kill();
};
```

I made sure to add a new 'trackingDistance' method in your Finder.cpp class to take 'ContourSegment'. (Note: the 'trackPoint' ofPoint variable should be calculated on instantiation in the constructor of 'ContourSegment')

``` c++
float trackingDistance(const ContourSegment &a, const ContourSegment &b) {
        float dx = a.trackPoint.x - b.trackPoint.x;
    float dy = a.trackPoint.y - b.trackPoint.y;
    return sqrtf(dx * dx + dy * dy);
}
```

Then, back in my TestApp I instantiate a custom 'TrackerFollower':

``` c++
ofxCv::TrackerFollower<ContourSegment, ConcaveSegmentFollower> concaveSegmentTracker;
```

...and pass it a vector of 'ContourSegments' in the track() method ('concaveSegments' is a vector<ContourSection>)

``` c++
concaveSegmentTracker.track(concaveSegments);
```

BUT :(
XCode tells me there's "No matching function for call to 'trackingDistance'" (in Tracker.h)
I've tried all sorts of stuff but I'm just scratching my head now.
Did I do something wrong?

**Comment by stephanschulz** [comment]
I have been using the rectTracker for a while but am always struggling to have each instance maintain it's own variables and changes.
The `example-contours-following` defines the followers like so in the update() function:
```
vector<Glow>& followers = tracker.getFollowers();
```
This erases any already existing changes inside the follower.

I made this example in which `myVar++` is called in Glow::draw() 
https://gist.github.com/stephanschulz/ce4326fac903d888e454f412fefc8068#file-ofapp-cpp-L45

But `myVar` never increases.

On the other hand when I declare it like as a pointer  in `ofApp.h` `vector<Glow>* followers_0;` then myVar increases with every draw() call.

All seems well and happy.

But when I use this methodology in a larger app I get Thread related crashes like these:

![Screen Shot 2023-10-12 at 3 32 42 PM](https://github.com/kylemcdonald/ofxCv/assets/1054816/abf4cce4-e5af-4973-8c60-a8e4288fa9b4)

I am not sure if there is a saver way to achieve this or if I need to be very careful in how and when to call things?

**Comment by stephanschulz** [comment]
here you can see how the 2nd number in each follower only increases when I use the pointer implementation:


https://github.com/kylemcdonald/ofxCv/assets/1054816/65a93fea-391f-4041-ade4-4a100996e912

**Comment by artificiel** [comment]
what a casual necrobump!

I've not used the follower but passing around raw pointers (and/or references to raw pointers) is known to be a challenge; the kind of symptoms you have could be related to ownership/management. perhaps due for an upgrade to shared_ptr which (beyond sanitizing the lifecycle) may reveal otherwise silent design problems.
