### ISSUE TITLE
Excessive follower creation / destruction

### ISSUE THREAD

**Issue by philworthy** [kylemcdonald/ofxCv#86]
Hi Kyle.

I'm using your tracker with a custom follower class and was running into some problems (elsewhere in the code). When I logged everything I found that in the tracker.track() call many followers were being created and deleted (in a single frame). Was wondering if this is normal behaviour for the tracker or a sign of a problem.

Eg, this is from my console (should be self explanatory):

```
[verbose] tracker begin
[verbose] created follower 0
[verbose] deleted follower 0
[verbose] follower 0 setup
[verbose] created follower 0
[verbose] deleted follower 0
[verbose] deleted follower 0
[verbose] follower 0 setup
[verbose] created follower 0
[verbose] deleted follower 0
[verbose] deleted follower 1
[verbose] deleted follower 0
[verbose] follower 0 setup
[verbose] tracker end

```

Any ideas?

**Comment by kylemcdonald** [comment]
closing as impossible to replicate
